# -*- coding: utf-8 -*-
"""YoutubeToMP3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1p-ZzpY1xQvKMaKnhBwVNn6X3loUcI0

How to use.

Step1. Click Runtime tab and select 'Run all'.

Step2. Scroll down this page until you see 'convert_mp3()'

Step3. Copy and paste the link from YouTube.

Step4. Wait until you see 'Refresh Files directory and Download mp3 file'.

Step5. Go to Files and click Refresh icon.

Step6. Double click the file you downloaded.
"""

!pip install pydub
!pip install pytube

import os
from pytube import YouTube
from moviepy.audio.io.AudioFileClip import AudioFileClip

def convert_mp3():
  print('copy and paste the link from YouTube :')
  link = input()
  print('processing...')
  yt = YouTube(link)
  audio = yt.streams.filter(only_audio=True)
  index = 0
  abr = 0
  new_index = 0
  for a in audio:
    new_abr = int(a.abr.replace('kbps', ''))
    if new_abr > abr:
      index = new_index
      abr = new_abr
    new_index += 1
  fname = yt.title
  if not '/' in yt.title:
    audio[index].download('/content', filename=yt.title)
  else:
    fname = yt.title.replace('/', ' ')
    audio[index].download('/content', filename=fname)
  audio_inputpath = '/content/' + fname
  audio_outputpath = '/content/' + fname + '.mp3'
  with AudioFileClip(audio_inputpath) as audio:
    audio.write_audiofile(audio_outputpath)
  os.remove(audio_inputpath)
  print(yt.title + ' done')
  print('Refresh Files directory and Download mp3 file')

convert_mp3()